### ISSUE TITLE
DEBUG=True in production

### ISSUE THREAD

**Issue by narenchoudhary** [aishack/aishack#19]
[aishack.in](http://aishack.in) displays full stack of errors on request errors instead of custom error pages because `DEBUG` is set to `True` in `settings.py`. It's potentially insecure to keep `DEBUG=True` in production. If you're already aware of this, ignore this issue. 

I hope you're not using the same `SECRET_KEY` and `SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET` stated in `settings.py` in production version.

**Comment by liquidmetal** [comment]
Thanks for reporting these! I'll fix the `DEBUG=True` thing. I manually change the secrets for google oauth everytime I redeploy - so no need to worry about that.

**Comment by liquidmetal** [comment]
Put in appropriate automation in place to prevent `DEBUG=True` from happening again. Also, removed google oauth from the website - it was more painful to maintain and I didn't find it very useful.
